### ISSUE TITLE
rule engine error stomps underlying reason for a failure

### ISSUE THREAD

**Issue by trel** [irods/irods_rule_engine_plugin_logical_quotas#23]
- [x] main
- [x] 4-2-stable
---
Quota values look fine:
```
$ imeta ls -C /tempZone/logical/path
AVUs defined for collection /tempZone/logical/path:
attribute: irods::logical_quotas::maximum_number_of_data_objects
value: 10000
units:
----
attribute: irods::logical_quotas::maximum_size_in_bytes
value: 1000000000000
units:
----
attribute: irods::logical_quotas::total_number_of_data_objects
value: 1867
units:
----
attribute: irods::logical_quotas::total_size_in_bytes
value: 899259585008
units:
```

In the catalog:
```
$ ils -LAv /tempZone/logical/path/to/dataobject/file.log
  rods          0 demoResc      7704811 2020-11-04.16:35 & file.log
    sha2:weRCAlW/pbGQjGTkQlHkMdfovOXjlXvj36y+GQysk4k=    generic    /path/to/physical/file.log
        ACL - rods#tempZone:own  
```

Error on `iput` overwrite:
```
$ iput -f localfile /tempZone/logical/path/to/dataobject/file.log
remote addresses: 10.225.160.101 ERROR: putUtil: put error for /tempZone/logical/path/to/dataobject/file.log, status = -1205000 status = -1205000 RE_RUNTIME_ERROR
Level 0: Logical Quotas Policy: Could not open data object
```

This is very confusing... why are the quotas complaining?

rodsLog...
```
Nov  5 15:46:27 pid:5758 NOTICE: remoteFileOpen: rcFileOpen failed for /path/to/physical/file.log
Nov  5 15:46:27 pid:5758 NOTICE: dataOpen: l3Open of /path/to/physical/file.log failed, status = -510002
Nov  5 15:46:27 pid:5758 remote addresses: 10.225.128.219, 10.225.144.93, 10.225.160.80 ERROR: Logical Quotas Policy: Could not open data object
```

But that error is not logical quotas...
```
$ ierror 510002
irods error: -510002 UNIX_FILE_OPEN_ERR No such file or directory
```

This was later confirmed a real open error on disk, not iRODS.

However, the initial error message to the client was misleading/confusing/incomplete.

We should instead add to any existing error stack.

**Comment by korydraughn** [comment]
This is likely coming from the `pep_api_data_obj_put_pre` handler.
https://github.com/irods/irods_rule_engine_plugin_logical_quotas/blob/2c7c2e1f677b949bb32bf86414c9b2788da86a2b/src/handler.cpp#L833
The `size_on_disk` function is using `dstream` to get the size. It was done this way due to the catalog not always reflecting the correct size.
https://github.com/irods/irods_rule_engine_plugin_logical_quotas/blob/2c7c2e1f677b949bb32bf86414c9b2788da86a2b/src/handler.cpp#L451-L463
It may be a little tricky to get the error code for this particular case due to the fact that dstream objects never expose error codes.
